[workspace]
default-members = [
    "backend",
    "frontend/client",
    "frontend/gui",
    "frontend/cli"
]

members = [
    "backend",
    "frontend/client",
    "frontend/gui",
    "frontend/cli"
]